### ISSUE TITLE
Issues with demo

### ISSUE THREAD

**Issue by jondunning** [simith/builder_session_reinvent2019_fr#8]
Hey, just a quick note so you can send instructions once demo is fixed.

**Comment by tobysteward** [comment]
mail@tobysteward.com

**Comment by TurhanOz** [comment]
Please send instruction (today's aws reinvent workshop 20191202)

**Comment by simith** [comment]
The issue with code signing has been resolved, please login to your respective accounts, can you complete the remaining steps and let me know, how you go! Good luck. I will be resetting some of the things in the environment tomorrow, so if you could finish it by tonight, it will be perfect. Post updates on this ticket please.

**Comment by simith** [comment]
@jondunning  @TurhanOz  Please let me know.

**Comment by tobysteward** [comment]
We’ve got a new firmware build ready for rollout but our  connectivity isn’t great and the OTA update is failing so have queued it for rollout when back on AWS SSID - will let you know once it’s loaded up.
