### ISSUE TITLE
workshop

### ISSUE THREAD

**Issue by roylee17** [simith/builder_session_reinvent2019_fr#9]
roylee17@gmail.com

**Comment by simith** [comment]
The issue with code signing has been resolved, please login to your respective accounts, can you complete the remaining steps and let me know, how you go! Good luck. I will be resetting some of the things in the environment tomorrow, so if you could finish it by tonight, it will be perfect. Post updates here: https://github.com/simith/builder_session_reinvent2019_fr/issues/8
